#!/usr/bin/env ruby

require File.join(File.expand_path(File.dirname(__FILE__)),'lib/deduper')

del_dir = Dir.getwd

# raise ArgumentError,del_dir
totals = Deduper.dedupe(del_dir)

puts "\nTotals: #{totals.inspect}"
